### ISSUE TITLE
Gerer les Webhooks Stripe

### ISSUE THREAD

**Issue by MathLebl** [MathLebl/contre_pied_prod#188]

**Comment by Dadagis** [comment]
je vais me pencher sur la question mais j'ai toujours été un peu perdu avec Stripe :/
Si tu avais une idée de comment gérer le truc au moment ou tu avais mis en place le paiement hésites pas à m'en parler :)
J'ai vu qu'il y avait aussi un service stripe, je sais pas si c'est toi qui l'a crée ou non 🤔

**Comment by MathLebl** [comment]
En gros le(s) webhook(s) sont généré par Stripe, il peut renvoyer plein d'infos
Le service stripe dans l'app gère le retour du webhook stripe qui concerne le "state" de la commande et qui est sensé la faire passer de pending à payed.

Si tu veux tester les Webhooks en local par contre, il faut Ngroc, qui te génère une url éphémère et qu'il faut changer à chaque fois que tu coupes
