### ISSUE TITLE
Bouton de connexion

### ISSUE THREAD

**Issue by Dadagis** [MathLebl/contre_pied_prod#203]
Je serai d'avis de rajouter un bouton "Se connecter" visible directement, au lieu d'avoir à le chercher depuis le dropdown.
Le mec qui connait pas trop et qui fait pas gaffe il risque de tourner un bon moment avant de tomber sur la page d'inscription

**Comment by MathLebl** [comment]
Je suis d’accord, je pensais lui trouver une place dans la page boutique.

**Comment by Dadagis** [comment]
🤔 On pourrait tout simplement le rajouter partout à partir du moment ou l'utilisateur n'est pas connecté ?
C'est comme tu le sens

**Comment by Dadagis** [comment]
Bouton ajouté dans PR #216
